services:
  haus-muell-app:
    build: .
    container_name: haus-muell-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - "./data:/app/data"

